//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Data4Mat
{
	namespace TradeCalculator.Properties
	{
		using System;


		/// <summary>
		///   A strongly-typed resource class, for looking up localized strings, etc.
		/// </summary>
		// This class was auto-generated by the StronglyTypedResourceBuilder
		// class via a tool like ResGen or Visual Studio.
		// To add or remove a member, edit your .ResX file then rerun ResGen
		// with the /str option, or rebuild your VS project.
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
		internal class Resources
		{

			private static global::System.Resources.ResourceManager resourceMan;

			private static global::System.Globalization.CultureInfo resourceCulture;

			[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
			internal Resources()
			{
			}

			/// <summary>
			///   Returns the cached ResourceManager instance used by this class.
			/// </summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Resources.ResourceManager ResourceManager
			{
				get
				{
					if (object.ReferenceEquals(resourceMan, null))
					{
						global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data4Mat.TradeCalculator.Properties.Resources", typeof(Resources).Assembly);
						resourceMan = temp;
					}
					return resourceMan;
				}
			}

			/// <summary>
			///   Overrides the current thread's CurrentUICulture property for all
			///   resource lookups using this strongly typed resource class.
			/// </summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Globalization.CultureInfo Culture
			{
				get
				{
					return resourceCulture;
				}
				set
				{
					resourceCulture = value;
				}
			}

			/// <summary>
			///   Looks up a localized string similar to 0,EUR/USD,USD,100000,10,2,4,$
			///1,GBP/USD,USD,100000,10,3,4,$
			///2,AUD/USD,USD,100000,10,3,4,$
			///3,NZD/USD,USD,100000,10,6,4,$
			///.
			/// </summary>
			internal static string currencies
			{
				get
				{
					return ResourceManager.GetString("currencies", resourceCulture);
				}
			}

			/// <summary>
			///   Looks up a localized string similar to ..\..\Data\currencies.csv.
			/// </summary>
			internal static string CurrenciesDataFile
			{
				get
				{
					return ResourceManager.GetString("CurrenciesDataFile", resourceCulture);
				}
			}

			internal static System.Drawing.Icon D4M_Logo_Icon
			{
				get
				{
					object obj = ResourceManager.GetObject("D4M_Logo_Icon", resourceCulture);
					return ((System.Drawing.Icon)(obj));
				}
			}

			/// <summary>
			///   Looks up a localized string similar to 15.
			/// </summary>
			internal static string SlingShotOffset
			{
				get
				{
					return ResourceManager.GetString("SlingShotOffset", resourceCulture);
				}
			}
		}
	}
}